In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
from mpl_toolkits.mplot3d import Axes3D # for 3D plotting
mpl.rcParams['image.cmap'] = 'hot_r'
import os
import glob
import hgc_testbeam as hgc

In [2]:
hgc.runlist

,Run,Date,Nevents,Particle,Energy,Configuration,CaloConfiguration
136,384,2018-10-13 10:20:00,11958,electron,250,22b,1
137,385,2018-10-13 10:31:00,10161,electron,250,22b,1
138,386,2018-10-13 10:45:00,12097,electron,250,22b,1
140,389,2018-10-13 11:10:00,10305,electron,250,22b,1
141,390,2018-10-13 11:19:00,10880,electron,250,22b,1
142,391,2018-10-13 11:31:00,3326,electron,250,22b,1
143,392,2018-10-13 11:35:00,10204,electron,250,22b,1
144,393,2018-10-13 11:48:00,5196,electron,250,22b,1
145,397,2018-10-13 12:18:00,13521,electron,250,22b,1
146,398,2018-10-13 12:37:00,12614,electron,250,22b,1
147,399,2018-10-13 12:52:00,10269,electron,250,22b,1
151,404,2018-10-13 14:47:00,13199,electron,250,22b,1
152,405,2018-10-13 15:07:00,10300,electron,300,22b,1
153,406,2018-10-13 15:25:00,4619,electron,300,22b,1
154,407,2018-10-13 15:39:00,5049,electron,300,22b,1
155,408,2018-10-13 15:48:00,1742,electron,300,22b,1
158,411,2018-10-13 15:59:00,10366,electron,300,22b,1
159,412,2018-10-13 16:16:00,9680,electron,300,22b,1
161,414,2018-10-13 16:55:00,13285,electron,300,22b,1
162,415,2018-10-13 17:18:00,11321,electron,300,22b,1
163,416,2018-10-13 17:37:00,14581,electron,300,22b,1
165,418,2018-10-13 18:04:00,10126,electron,300,22b,1
166,419,2018-10-13 18:22:00,11189,electron,300,22b,1
167,420,2018-10-13 18:40:00,10242,electron,300,22b,1
168,421,2018-10-13 18:57:00,7314,electron,300,22b,1
169,422,2018-10-13 19:14:00,10478,electron,300,22b,1
170,423,2018-10-13 19:31:00,6820,electron,300,22b,1
171,424,2018-10-13 20:05:00,11528,electron,300,22b,1
172,425,2018-10-13 20:29:00,11593,electron,300,22b,1
173,426,2018-10-13 20:47:00,2757,electron,300,22b,1
...,...,...,...,...,...,...,...
650,1125,2018-10-23 10:41:00,10470,pion,200,24a,3
651,1126,2018-10-23 11:28:00,9701,pion,200,24a,3
652,1127,2018-10-23 11:59:00,10076,pion,120,24a,3
653,1128,2018-10-23 12:30:00,10027,pion,120,24a,3
654,1129,2018-10-23 13:27:00,10107,pion,120,24a,3
656,1131,2018-10-23 14:33:00,10030,pion,30,24a,3
657,1132,2018-10-23 15:25:00,2060,pion,30,24a,3
658,1134,2018-10-23 16:28:00,10255,pion,30,24a,3
659,1135,2018-10-23 17:32:00,10132,pion,30,24a,3
660,1136,2018-10-23 18:39:00,10121,pion,30,24a,3
661,1139,2018-10-23 19:48:00,10210,electron,50,24a,3
662,1141,2018-10-23 20:12:00,10449,electron,50,24a,3
663,1144,2018-10-23 20:38:00,10079,electron,50,24a,3
664,1145,2018-10-23 21:09:00,10292,electron,50,24a,3
665,1146,2018-10-23 21:10:00,10007,electron,50,24a,3
666,1147,2018-10-23 22:02:00,10210,electron,150,24a,3
667,1149,2018-10-23 22:20:00,10918,electron,150,24a,3
668,1151,2018-10-23 22:43:00,10142,electron,150,24a,3
669,1153,2018-10-23 23:02:00,10061,electron,300,24a,3
670,1154,2018-10-23 23:40:00,10064,electron,300,24a,3
671,1155,2018-10-24 00:15:00,10093,electron,300,24a,3
672,1156,2018-10-24 00:55:00,10058,pion,150,24a,3
673,1157,2018-10-24 01:22:00,10062,pion,150,24a,3
675,1159,2018-10-24 02:01:00,10481,pion,150,24a,3
676,1160,2018-10-24 02:33:00,10658,pion,150,24a,3
677,1163,2018-10-24 03:07:00,10091,pion,150,24a,3
678,1164,2018-10-24 03:36:00,10157,pion,300,24a,3
679,1165,2018-10-24 04:01:00,10044,pion,300,24a,3
680,1166,2018-10-24 04:26:00,10068,pion,300,24a,3
681,1167,2018-10-24 05:12:00,11742,pion,50,24a,3

In [ ]:
hdf = hgc.load_run(384)
hdf.keys()

In [12]:
hdf = hgc.load_run(384, columns = ["beamEnergy","event", "rechit_layer", "rechit_energy", "rechit_x", "rechit_y", "rechit_z"])
hdf

                beamEnergy  event  rechit_layer  rechit_energy   rechit_x  \
entry subentry
0     0              250.0      1             1       9.392921  -0.974487
      1              250.0      1             1       0.895975  -3.897949
      2              250.0      1             1       1.230205   3.897949
      3              250.0      1             1       2.680023   3.897949
      4              250.0      1             1       0.509546   2.923340
      5              250.0      1             2       2.672407  -0.000009
      6              250.0      1             2       2.351642  -0.000009
      7              250.0      1             2       3.388553  -0.974487
      8              250.0      1             2      37.912022  -0.974487
      9              250.0      1             2       3.437580  -1.948975
      10             250.0      1             2       0.960972  -2.923340
      11             250.0      1             2      19.188520  -3.897949
      12             250.0      1             2       1.414547  -4.872070
      13             250.0      1             3       6.981477  -0.000009
      14             250.0      1             3       2.641762  -0.000009
      15             250.0      1             3       2.770968  -0.000009
      16             250.0      1             3       0.981798  -0.974487
      17             250.0      1             3      97.006668  -0.974487
      18             250.0      1             3       4.429567  -1.948975
      19             250.0      1             3      19.055336  -1.948975
      20             250.0      1             3      34.972244  -1.948975
      21             250.0      1             3      14.445088  -2.923340
      22             250.0      1             3       1.621327  -2.923340
      23             250.0      1             3       4.422503  -2.923340
      24             250.0      1             3       7.532519  -2.923340
      25             250.0      1             3       1.866047  -3.897949
      26             250.0      1             3      71.467850  -3.897949
      27             250.0      1             3       3.008772  -3.897949
      28             250.0      1             3       1.549728  -3.897949
      29             250.0      1             3       3.250007  -4.872070
...                    ...    ...           ...            ...        ...
11957 1048           250.0  11958            37       0.313660  -0.974487
      1049           250.0  11958            37       0.237658  -1.948975
      1050           250.0  11958            37       0.431634  -2.923340
      1051           250.0  11958            37       0.361474  -4.872070
      1052           250.0  11958            37       0.440493   2.923340
      1053           250.0  11958            37       0.427345   1.948975
      1054           250.0  11958            37       0.332197   0.974487
      1055           250.0  11958            37       0.238569   0.974487
      1056           250.0  11958            37       0.264169   3.897949
      1057           250.0  11958            37       0.655751 -13.642578
      1058           250.0  11958            37       0.498066 -15.591797
      1059           250.0  11958            37       0.460335 -16.566406
      1060           250.0  11958            37       0.373271 -13.642578
      1061           250.0  11958            37       4.834332 -14.617188
      1062           250.0  11958            37       0.443329   7.795898
      1063           250.0  11958            37       1.955462  14.617188
      1064           250.0  11958            37       0.361279  15.591797
      1065           250.0  11958            37       0.323169  15.591797
      1066           250.0  11958            37       0.350064  14.617188
      1067           250.0  11958            37       0.374143  12.667969
      1068           250.0  11958            37       0.439544   4.872070
      1069           250.0  11958            37      26.438944 -15.591797
      1070           250.0  11958            37       0.369792  -9.744141
      1071           250.0  11958            37       0.318969   1.948975
      1072           250.0  11958            37       0.391893  -1.948975
      1073           250.0  11958            38       0.282974   3.897949
      1074           250.0  11958            38       0.444346   1.948975
      1075           250.0  11958            40       0.394940  -2.923340
      1076           250.0  11958            40       0.314217  -3.897949
      1077           250.0  11958            40       0.305004  -4.872070

                 rechit_y    rechit_z
entry subentry
0     0          0.562622   13.320000
      1          3.375488   13.320000
      2         -2.250488   13.320000
      3         -4.500977   13.320000
      4         -3.937988   13.320000
      5         -0.000009   14.210000
      6          1.125244   14.210000
      7         -0.562622   14.210000
      8          0.562622   14.210000
      9          1.125244   14.210000
      10        -5.063477   14.210000
      11         3.375488   14.210000
      12         3.937988   14.210000
      13        -1.125244   16.580000
      14         3.375488   16.580000
      15         1.125244   16.580000
      16        -0.562622   16.580000
      17         0.562622   16.580000
      18        -1.125244   16.580000
      19         1.125244   16.580000
      20        -0.000009   16.580000
      21        -1.687744   16.580000
      22         2.812988   16.580000
      23         1.687744   16.580000
      24         0.562622   16.580000
      25         4.500977   16.580000
      26         3.375488   16.580000
      27         2.250488   16.580000
      28        -0.000009   16.580000
      29         2.812988   16.580000
...                   ...         ...
11957 1048       5.063477  121.167999
      1049       3.375488  121.167999
      1050       1.687744  121.167999
      1051      -1.687744  121.167999
      1052       5.063477  121.167999
      1053       4.500977  121.167999
      1054       5.063477  121.167999
      1055       2.812988  121.167999
      1056      -7.875977  121.167999
      1057      -2.250488  121.167999
      1058      -9.001953  121.167999
      1059      -6.188477  121.167999
      1060      10.126953  121.167999
      1061      10.689453  121.167999
      1062       9.001953  121.167999
      1063       1.687744  121.167999
      1064      -4.500977  121.167999
      1065      -9.001953  121.167999
      1066      -6.188477  121.167999
      1067      -8.439453  121.167999
      1068       3.937988  121.167999
      1069      -2.250488  121.167999
      1070      -0.000009  121.167999
      1071       3.375488  121.167999
      1072     -15.751953  121.167999
      1073       1.125244  129.098007
      1074      -2.250488  129.098007
      1075      -1.687744  144.018005
      1076      -1.125244  144.018005
      1077       2.812988  144.018005

[12805085 rows x 7 columns]

In [16]:
hdf.beamEnergy[0][0]

300.0

In [2]:
electron_runlist = hgc.runlist.query("Particle == 'electron'").query('Configuration == "23c"').query('Energy == "300"')
electron_runlist

,Run,Date,Nevents,Particle,Energy,Configuration,CaloConfiguration
502,918,2018-10-19 16:54:00,10057,electron,300,23c,2
503,919,2018-10-19 17:34:00,10197,electron,300,23c,2
504,920,2018-10-19 18:13:00,11640,electron,300,23c,2
543,964,2018-10-20 15:15:00,1612,electron,300,23c,2
544,965,2018-10-20 15:22:00,10086,electron,300,23c,2
545,967,2018-10-20 16:26:00,10138,electron,300,23c,2
546,968,2018-10-20 16:54:00,10134,electron,300,23c,2
547,969,2018-10-20 17:25:00,10237,electron,300,23c,2
578,1005,2018-10-21 08:33:00,3083,electron,300,23c,2
579,1006,2018-10-21 13:55:00,1041,electron,300,23c,2

In [3]:
rechit_energy_mean = []
rechit_energy_variance = []
rechit_x_mean = []
rechit_x_variance = []
rechit_y_mean = []
rechit_y_variance = []
rechit_z_mean = []
rechit_z_variance = []
configuration = []
energy = []

In [4]:
run_numbers = electron_runlist.Run.values
Config = electron_runlist.Configuration
for (run,Configuration) in zip (run_numbers,Config):
    hdf = hgc.load_run(run, columns = ["beamEnergy","event", "rechit_layer", "rechit_energy", "rechit_x", "rechit_y", "rechit_z"])
    configuration.append(Configuration)
    energy.append(hdf.beamEnergy[0][0])
    rechit_energy_mean.append(hdf.rechit_energy.mean())
    rechit_energy_variance.append(hdf.rechit_energy.std())
    rechit_x_mean.append(hdf.rechit_x.mean())
    rechit_x_variance.append(hdf.rechit_x.std())
    rechit_y_mean.append(hdf.rechit_x.mean())
    rechit_y_variance.append(hdf.rechit_x.std())
    rechit_z_mean.append(hdf.rechit_x.mean())
    rechit_z_variance.append(hdf.rechit_x.std())

Type = pd.DataFrame({
    "energy_mean" : rechit_energy_mean,
    "energy_variance" : rechit_energy_variance,
    "x_mean" : rechit_x_mean,
    "x_variance" : rechit_x_variance,
    "y_mean" : rechit_y_mean,
    "y_variance" : rechit_y_variance,
    "z_mean" : rechit_z_mean,
    "z_variance" : rechit_z_variance,
    "configuration" : configuration,
    "Beam_energy" : energy    
})
Type

,energy_mean,energy_variance,x_mean,x_variance,y_mean,y_variance,z_mean,z_variance,configuration,Beam_energy
0,21.171623,82.762100,-0.587678,3.424203,-0.587678,3.424203,-0.587678,3.424203,23c,300.0
1,21.158806,82.647446,-0.583291,3.422520,-0.583291,3.422520,-0.583291,3.422520,23c,300.0
2,21.133535,82.479088,-0.583520,3.421154,-0.583520,3.421154,-0.583520,3.421154,23c,300.0
3,21.041883,81.689644,-0.570656,3.419888,-0.570656,3.419888,-0.570656,3.419888,23c,300.0
4,21.021444,81.465836,-0.566303,3.422700,-0.566303,3.422700,-0.566303,3.422700,23c,300.0
5,21.018089,81.422348,-0.565329,3.421283,-0.565329,3.421283,-0.565329,3.421283,23c,300.0
6,21.022806,81.254318,-0.561968,3.418531,-0.561968,3.418531,-0.561968,3.418531,23c,300.0
7,21.026205,81.249870,-0.566388,3.417003,-0.566388,3.417003,-0.566388,3.417003,23c,300.0
8,21.173666,82.768707,-0.584201,3.432621,-0.584201,3.432621,-0.584201,3.432621,23c,300.0
9,21.147253,82.765877,-0.573909,3.427868,-0.573909,3.427868,-0.573909,3.427868,23c,300.0

In [ ]:
check_run = 392
#check_event = 3000
check_hdf = hgc.load_run(check_run, columns = ["beamEnergy","event", "rechit_layer", "rechit_energy", "rechit_x", "rechit_y", "rechit_z"])
rechit_energy_mean.append(hdf.rechit_energy.mean())
rechit_energy_variance.append(hdf.rechit_energy.std())
rechit_x_mean.append(hdf.rechit_x.mean())
rechit_x_variance.append(hdf.rechit_x.std())
rechit_y_mean.append(hdf.rechit_x.mean())
rechit_y_variance.append(hdf.rechit_x.std())
rechit_z_mean.append(hdf.rechit_x.mean())
rechit_z_variance.append(hdf.rechit_x.std())